### ISSUE TITLE
useDexieGetTable question

### ISSUE THREAD

**Issue by xygcxy** [ttessarolo/useDexie#2]
Hello
The useDexieGetTable hook. When the previous data is empty array, current data is also empty array. It seems don't return the current new result.
when I add options into the dependence  it can return data but it's previous data. I'm not sure how to get the new result.
```
export function useDexieGetTable(Table, opts) {
.......
useEffect(() => {
    if (data && cbRef.current) {
      cbRef.current(data);
      cbRef.current = undefined;
    }
  }, [data, options]);

  return func;
}
```

**Comment by ttessarolo** [comment]
Can you show me a code example of how you use this hook?

**Comment by xygcxy** [comment]
Thank you to watch this question.
You can check this link https://codesandbox.io/s/tender-dawn-tkg60?file=/src/App.js
when I first click 'T3' line, console panel print '[]', then I click 'T4' line, it does not print '[]',  I muse click twice 'T4' line it can print '[]'.
I notice this code `!isEqual(dataRef.current, data)` When the two data compared are '[]', it will not execute `setRawData(data)`; 😂

**Comment by xygcxy** [comment]
> Can you show me a code example of how you use this hook?

Thank you to watch this question.
You can check this link https://codesandbox.io/s/tender-dawn-tkg60?file=/src/App.js
when I first click 'T3' line, console panel print '[]', then I click 'T4' line, it does not print '[]', I must click twice 'T4' line it can print '[]'.
I notice this code !isEqual(dataRef.current, data) When the two data compared are '[]', it will not execute setRawData(data); 😂

**Comment by ttessarolo** [comment]
I you return two empty Arrays id doesn't execute the second time. It's correct. Ar I'm missing something?

**Comment by xygcxy** [comment]
> I you return two empty Arrays id doesn't execute the second time. It's correct. Ar I'm missing something?
I mean When you switch and click two rows of data, the second clicked row needs to be clicked twice to return the data.Sometimes What I need is to return data in the callback every time I switch and click, regardless of whether it is an empty array. I am not sure if I use it in right way.

**Comment by xygcxy** [comment]
> I you return two empty Arrays id doesn't execute the second time. It's correct. Ar I'm missing something?
I mean When you switch and click two rows of data, the second clicked row needs to be clicked twice to return the data.Sometimes What I need is to return data in the callback every time I switch and click, regardless of whether it is an empty array. Because although the two data are empty in indexDB, the conditions of each query are different. I am not sure if I use it in right way.
